### PR TITLE
style: fix aspect ratio with max height

### PR DESCRIPTION
**Pull request by bhagyamudgal**

### CODE REVIEW

**Comment by zhelezkov** [comment]
hey @bhagyamudgal, after testing height limit set to 500px, we found out that it's a bit insufficient for some use cases, when blinks container width is more than 500px image get's cropped

After discussing with team, we think that best solution will be to limit maximum image height to it's container width. how do you feel about this approach? this way we get rid of abnormally tall images, and keep the 'safe' 1/1 aspect ration as a maximum

I've pushed my proposed changes: https://github.com/dialectlabs/blinks/pull/10/commits/1fe92cc026f91cadf4ee8033429f7790eae822ba

**Review by fsher — APPROVED** [review]
nicely done, great to see this solved! thanks everyone!

**Comment by bhagyamudgal** [comment]
> hey @bhagyamudgal, after testing height limit set to 500px, we found out that it's a bit insufficient for some use cases, when blinks container width is more than 500px image get's cropped
> 
> After discussing with team, we think that best solution will be to limit maximum image height to it's container width. how do you feel about this approach? this way we get rid of abnormally tall images, and keep the 'safe' 1/1 aspect ration as a maximum
> 
> I've pushed my proposed changes: [1fe92cc](https://github.com/dialectlabs/blinks/commit/1fe92cc026f91cadf4ee8033429f7790eae822ba)

Yeah I think this approach is good

**Comment by zhelezkov** [comment]
great, we'll get it shipped then!

**Pull request merged**
